//Name: Arun Sharma
//Date: 10/27/2024
//Assignment name and number: Module 1: Binary I/O - Assignment 1

//Sources : https://www.w3schools.com/ , https://www.geeksforgeeks.org/
//Purpose of code: This program reads and displays the data from the file created by DataFileWriter, verifying data storage and retrieval functions.
//Github link: https://github.com/SharmaArun017/CSD-420

package module1.assignment1;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;

public class DataFileReader {
    public static void main(String[] args) {
        try (DataInputStream dis = new DataInputStream(new FileInputStream("ArunDatafile.dat"))) {
            // Read integers from file
            int[] randomIntegers = new int[5];
            for (int i = 0; i < randomIntegers.length; i++) {
                randomIntegers[i] = dis.readInt();
            }

            // Read the date from file
            long dateMillis = dis.readLong();
            Date currentDate = new Date(dateMillis);

            // Read doubles from file
            double[] randomDoubles = new double[5];
            for (int i = 0; i < randomDoubles.length; i++) {
                randomDoubles[i] = dis.readDouble();
            }

            // Display the data
            System.out.println("Random Integers:");
            for (int value : randomIntegers) {
                System.out.print(value + " ");
            }
            System.out.println("\nCurrent Date: " + currentDate);
            System.out.println("Random Doubles:");
            for (double value : randomDoubles) {
                System.out.print(value + " ");
            }
        } catch (IOException e) {
            System.out.println("An error occurred while reading from the file.");
            e.printStackTrace();
        }
    }
}

/*
Step-by-Step Explanation:

Program 2 - DataFileReader:

1. Class Declaration:
   - The `DataFileReader` class is created to handle reading data from the file generated by `DataFileWriter` and displaying it.

2. Import Statements:
   - The `java.io.*` and `java.util.*` packages are imported to access classes like `DataInputStream`, `FileInputStream`, and `Date`.

3. Method Declaration - main(String[] args):
   - The `main` method is the program's entry point, handling the file reading and data display.

4. Reading the Integer Array:
   - A `DataInputStream` object is created to read data from the file "ArunDatafile.dat" (or your name’s version).
   - An integer array, `randomIntegers`, is initialized to store the five integers read from the file.

5. Reading the Date Object:
   - The `DataInputStream` reads a `long` value representing the timestamp of `currentDate` and converts it back into a `Date` object for display.

6. Reading the Double Array:
   - A double array, `randomDoubles`, is initialized to store the five double values read from the file.

7. Displaying the Data:
   - The program displays the integers, date, and double values to the console in a structured format, confirming the file's contents have been read and interpreted correctly.

Purpose:
   - This program pair is designed to generate random data (integers, doubles, and a date), store it in a file, and then read and display the data. It demonstrates Java I/O operations using `DataOutputStream` and `DataInputStream`.

Redo Notes:
   - To redo this program, modify the arrays' sizes or ranges, change the file name, or add additional data elements to test flexibility. To test reading, ensure the order of written data matches the order read.
*/